sm7250-common: Define TARGET_GRALLOC_HANDLE_HAS_RESERVED_SIZE - Updated display stack requires to use GRALLOC_HANDLE_HAS_RESERVED_SIZE
[Fixing following error]:
hardware/qcom-caf/sm8150/display/gralloc/gr_buf_mgr.cpp:107:43: error: no member named 'reserved_size' in 'private_handle_t'
  uint64_t reserved_region_size = handle->reserved_size;

Signed-off-by: Niranjan BR <niranjankannan2003@gmail.com>